fix bug elastic and others

diff --git a/compose/bin/setup b/compose/bin/setup
--- a/compose/bin/setup
+++ b/compose/bin/setup
@@ -7,21 +7,23 @@ source env/db.env
 source env/magento.env
 
 BASE_URL=${1:-magento2.local}
-ES_HOST=elasticsearch
+ES_HOST=elasticsearch1
 ES_PORT=9200
+
+curl -XPUT 'http://magento2.local:9200/_cluster/settings' -H 'Content-Type: application/json' -d '{"persistent" : {"cluster.routing.allocation.disk.watermark.flood_stage": "99%","cluster.routing.allocation.disk.watermark.high": "98%","cluster.routing.allocation.disk.watermark.low": "95%"}}'
 
 docker-compose stop && docker-compose up -d
 [ $? != 0 ] && echo "Failed to start Docker services" && exit
 
 bin/clinotty chmod u+x bin/magento
 
-echo "Waiting for connection to Elasticsearch..."
-bin/clinotty timeout 30 bash -c "
-    until curl --silent --output /dev/null http://$ES_HOST:$ES_PORT/_cat/health?h=st; do
-        printf '.'
-        sleep 5
-    done"
-[ $? != 0 ] && echo "Failed to connect to Elasticsearch" && exit
+#echo "Waiting for connection to Elasticsearch..."
+#bin/clinotty timeout 30 bash -c "
+#    until curl --silent --output /dev/null http://$BASE_URL:$ES_PORT/_cat/health?h=st; do
+#        printf '.'
+#        sleep 5
+#    done"
+#[ $? != 0 ] && echo "Failed to connect to Elasticsearch" && exit
 
 bin/clinotty bin/magento setup:install \
   --db-host="$MYSQL_HOST" \
@@ -41,8 +43,8 @@ bin/clinotty bin/magento setup:install \
   --timezone="$MAGENTO_TIMEZONE" \
   --amqp-host=rabbitmq \
   --amqp-port=5672 \
-  --amqp-user=guest \
-  --amqp-password=guest \
+  --amqp-user=magento \
+  --amqp-password=magento \
   --amqp-virtualhost=/ \
   --cache-backend=redis \
   --cache-backend-redis-server=redis \
@@ -55,8 +57,9 @@ bin/clinotty bin/magento setup:install \
   --session-save-redis-log-level=4 \
   --session-save-redis-db=2 \
   --search-engine=elasticsearch7 \
-  --elasticsearch-host=$ES_HOST \
-  --elasticsearch-port=$ES_PORT \
+  --elasticsearch-host=elasticsearch1 \
+  --elasticsearch-port=9200 \
+  --elasticsearch-index-prefix=magento \
   --use-rewrites=1
 
 echo "Copying files from container to host after install..."
@@ -73,9 +76,6 @@ bin/clinotty bin/magento indexer:reindex
 
 echo "Clearing the cache to apply updates..."
 bin/clinotty bin/magento cache:flush
-
-echo "Generating SSL certificate..."
-bin/setup-ssl "$BASE_URL"
 
 echo "Docker development environment setup complete."
 echo "You may now access your Magento instance at https://${BASE_URL}/"
